#!/bin/sh
#
# 2014-2015 ungleich GmbH (cdist at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

groups=$(cat "$__object/parameter/group")
state=$(cat "$__object/parameter/state")

cd "$__type/files"

if [ -f "$__object/parameter/user" ]; then
    user=$(cat "$__object/parameter/user")
else
    user="$__object_id"
fi
    

# check for existence first
for group in $groups; do
    if [ ! -d "$__type/files/$group" ]; then
        echo "Group $group does not exist, aborting" >&2
        exit 1
    fi
    if [ "$(ls "$__type/files/$group" | wc -l)" -lt 1 ]; then
        echo "Empty group $group - exiting"
        exit 1
    fi
done

for group in $groups; do
    # reset $@
    set --

    cd "$__type/files/$group"

    for key in *.pub; do
        set -- "$@" --key
        set -- "$@" "$(cat "$key")"
    done

    __ssh_authorized_keys "$user-$group" \
        --owner "$user" --state "$state" "$@"
done
